site_name: Gufo SNMP
site_description: Gufo SNMP Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_snmp/"
copyright: "&copy; 2023, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_snmp/
repo_name: gufolabs/gufo_snmp
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - Overview: examples/index.md
      - Single Item Get Request: examples/get.md
      - Multi Items Get Request: examples/getmany.md
      - GetNext Request: examples/getnext.md
      - GetBulk Request: examples/getbulk.md
      - Fetch: examples/fetch.md
      - SNMPv3 Get Request: examples/get-v3.md
      - SNMPv3 Engine ID Discovery: examples/engine-id-discovery.md
      - Rate Limiting: examples/ratelimit.md
      - Debugging: examples/debugging.md
  - Reference: reference/
  - Developers' Guide:
      - Developer's Environment: environment.md
      - Building and Testing: testing.md
      - Common Tasks: devcommon.md
      - Code Quality: codequality.md
      - Code Base: codebase.md
      - Contributing Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Supported Standards: standards.md
      - Supported BER Types: types.md
  - Benchmarks: benchmarks.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
watch:
  - docs/
  - src/gufo/
  - examples/
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_submodules: false
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-GW3X378HNJ
