site_name: Gufo SNMP
site_description: Gufo SNMP Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_snmp/"
copyright: "&copy; 2023, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_snmp/
repo_name: gufolabs/gufo_snmp
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - Overview: examples/index.md
      - Sync Mode:
          - Overview: examples/sync/index.md
          - Single Item Get Request: examples/sync/get.md
          - Multi Items Get Request: examples/sync/getmany.md
          - GetNext Request: examples/sync/getnext.md
          - GetBulk Request: examples/sync/getbulk.md
          - Fetch: examples/sync/fetch.md
          - SNMPv3 Get Request: examples/sync/get-v3.md
          - SNMPv3 Engine ID Discovery: examples/sync/engine-id-discovery.md
          - Rate Limiting: examples/sync/ratelimit.md
          - Debugging: examples/sync/debugging.md
      - Async Mode:
          - Overview: examples/async/index.md
          - Single Item Get Request: examples/async/get.md
          - Multi Items Get Request: examples/async/getmany.md
          - GetNext Request: examples/async/getnext.md
          - GetBulk Request: examples/async/getbulk.md
          - Fetch: examples/async/fetch.md
          - SNMPv3 Get Request: examples/async/get-v3.md
          - SNMPv3 Engine ID Discovery: examples/async/engine-id-discovery.md
          - Rate Limiting: examples/async/ratelimit.md
          - Debugging: examples/async/debugging.md
  - Reference: reference/
  - Benchmarks: benchmarks/
  - Developers' Guide:
      - Overview: dev/index.md
      - Developer's Environment: dev/environment.md
      - Building and Testing: dev/testing.md
      - Common Tasks: dev/common.md
      - Code Quality: dev/codequality.md
      - Code Base: dev/codebase.md
      - Contributing Guide: dev/CONTRIBUTING.md
      - Code of Conduct: dev/CODE_OF_CONDUCT.md
      - Supported Standards: dev/standards.md
      - Supported BER Types: dev/types.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
watch:
  - docs/
  - src/gufo/
  - examples/
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_submodules: false
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
extra:
  analytics:
    provider: google
    property: G-GW3X378HNJ
  "yes": ":material-check:"
  "no": ":material-close:"
