# ---------------------------------------------------------------------
# Gufo SNMP: _fast typing
# ---------------------------------------------------------------------
# Copyright (C) 2023-25, Gufo Labs
# See LICENSE.md for details
# ---------------------------------------------------------------------

# Python modules
from typing import Dict, List, Optional, Tuple, Union

# Gufo Labs modules
from .typing import ValueType

class SnmpError(Exception): ...
class SnmpEncodeError(SnmpError): ...
class SnmpDecodeError(SnmpError): ...
class SnmpAuthError(SnmpError): ...  # v3 only
class NoSuchInstance(SnmpError): ...

class GetIter(object):
    def __init__(
        self, oid: str, max_repetitions: Optional[int] = None
    ) -> None: ...

class SnmpV1ClientSocket(object):
    def __init__(
        self,
        addr: str,
        community: str,
        tos: int,
        send_buffer_size: int,
        recv_buffer_size: int,
        timeout_ns: int,
    ) -> None: ...
    def get_fd(self) -> int: ...

    # .get()
    def get(self, oid: str) -> ValueType: ...
    def send_get(self, oid: str) -> None: ...
    def recv_get(self) -> ValueType: ...

    # .get_many()
    def get_many(self, oids: List[str]) -> Dict[str, ValueType]: ...
    def send_get_many(self, oids: List[str]) -> None: ...
    def recv_get_many(
        self,
    ) -> Dict[str, ValueType]: ...

    # .get_next
    def get_next(self, iter_getnext: GetIter) -> Tuple[str, ValueType]: ...
    def send_get_next(self, iter_getnext: GetIter) -> None: ...
    def recv_get_next(
        self, iter_getnext: GetIter
    ) -> Tuple[str, ValueType]: ...

    # .get_bulk()
    def get_bulk(
        self, iter_getbulk: GetIter
    ) -> List[Union[Tuple[str, ValueType], None]]: ...
    def send_get_bulk(self, iter_getbulk: GetIter) -> None: ...
    def recv_get_bulk(
        self, iter_getnext: GetIter
    ) -> List[Union[Tuple[str, ValueType], None]]: ...

class SnmpV2cClientSocket(object):
    def __init__(
        self,
        addr: str,
        community: str,
        tos: int,
        send_buffer_size: int,
        recv_buffer_size: int,
        timeout_ns: int,
    ) -> None: ...
    def get_fd(self) -> int: ...
    # .get()
    def get(self, oid: str) -> ValueType: ...
    def send_get(self, oid: str) -> None: ...
    def recv_get(self) -> ValueType: ...
    # .get_many
    def get_many(self, oids: List[str]) -> Dict[str, ValueType]: ...
    def send_get_many(self, oids: List[str]) -> None: ...
    def recv_get_many(
        self,
    ) -> Dict[str, ValueType]: ...
    # .get_next()
    def get_next(self, iter_getnext: GetIter) -> Tuple[str, ValueType]: ...
    def send_get_next(self, iter_getnext: GetIter) -> None: ...
    def recv_get_next(
        self, iter_getnext: GetIter
    ) -> Tuple[str, ValueType]: ...
    # .get_bulk()
    def get_bulk(
        self, iter_getbulk: GetIter
    ) -> List[Union[Tuple[str, ValueType], None]]: ...
    def send_get_bulk(self, iter_getbulk: GetIter) -> None: ...
    def recv_get_bulk(
        self, iter_getnext: GetIter
    ) -> List[Union[Tuple[str, ValueType], None]]: ...

class SnmpV3ClientSocket(object):
    def __init__(
        self,
        addr: str,
        engine_id: bytes,
        user_name: str,
        auth_alg: int,
        auth_key: bytes,
        priv_alg: int,
        priv_key: bytes,
        tos: int,
        send_buffer_size: int,
        recv_buffer_size: int,
        timeout_ns: int,
    ) -> None: ...
    def set_keys(
        self,
        user_name: str,
        auth_alg: int,
        auth_key: bytes,
        priv_alg: int,
        priv_key: bytes,
    ) -> None: ...
    def get_fd(self) -> int: ...
    def get_engine_id(self) -> bytes: ...
    # .get()
    def get(self, oid: str) -> ValueType: ...
    def send_get(self, oid: str) -> None: ...
    def recv_get(self) -> ValueType: ...
    # .get_many()
    def send_get_many(self, oids: List[str]) -> None: ...
    def recv_get_many(
        self,
    ) -> Dict[str, ValueType]: ...
    def get_many(self, oids: List[str]) -> Dict[str, ValueType]: ...
    # .get_next
    def get_next(self, iter_getnext: GetIter) -> Tuple[str, ValueType]: ...
    def send_get_next(self, iter_getnext: GetIter) -> None: ...
    def recv_get_next(
        self, iter_getnext: GetIter
    ) -> Tuple[str, ValueType]: ...
    # Rest
    def get_bulk(
        self, iter_getbulk: GetIter
    ) -> List[Union[Tuple[str, ValueType], None]]: ...
    def send_get_bulk(self, iter_getbulk: GetIter) -> None: ...
    def recv_get_bulk(
        self, iter_getnext: GetIter
    ) -> List[Union[Tuple[str, ValueType], None]]: ...
    # .refresh
    def refresh(self) -> None: ...
    def send_refresh(self) -> None: ...
    def recv_refresh(self) -> None: ...

def get_master_key(auth_alg: int, passwd: bytes) -> bytes: ...
def get_localized_key(
    auth_alg: int, passwd: bytes, engine_id: bytes
) -> bytes: ...
