name: Package
env:
  PIP_CACHE_DIR: .pip
  PYTHONPATH: src
on:
  release:
    types: ["published"]
  workflow_dispatch: {}
jobs:
  build-sdist:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Upgrade Build
        run: pip install --upgrade build

      - name: Install Python Dependencies
        run: pip install -IU -r ./.requirements/build.txt

      - name: Build sdist
        run: ./tools/build/build-sdist.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  build-linux-amd64:
    runs-on: ubuntu-24.04
    needs: build-sdist
    strategy:
      fail-fast: true
      matrix:
        image:
          - manylinux2014_x86_64
          - manylinux_2_28_x86_64
          - musllinux_1_2_x86_64
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build wheels
        run: ./tools/build/build-linux.sh ${{matrix.image}}

      - name: Save Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel-linux-amd64-${{matrix.image}}
          path: wheelhouse/*.whl

  build-linux-aarch64:
    runs-on: ubuntu-24.04-arm
    needs: build-sdist
    strategy:
      fail-fast: true
      matrix:
        image:
          - manylinux_2_28_aarch64
          - musllinux_1_2_aarch64
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build wheels
        run: ./tools/build/build-linux.sh ${{matrix.image}}

      - name: Save Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel-linux-aarch64-${{matrix.image}}
          path: wheelhouse/*.whl

  # build-wheel-macos:
  #   runs-on: macos-11
  #   needs: build-sdist
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       include:
  #         - arch: x86_64
  #           platform: macosx
  #         # - arch: arm64
  #         #   platform: macosx
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4

  #     - name: Build Packages
  #       uses: pypa/cibuildwheel@v2.11.2
  #       env:
  #         SETUP_RUST_PLATFORM: ${{matrix.platform}}-${{matrix.arch}}
  #         CIBW_BUILD: cp{38,39,310,311}-${{matrix.platform}}_${{matrix.arch}}
  #         CIBW_ARCHS: ${{matrix.arch}}
  #         CIBW_ENVIRONMENT: >-
  #           PATH=$HOME/.cargo/bin:$PATH
  #           CARGO_HOME=$HOME/.cargo
  #           RUSTUP_HOME=$HOME/.rustup
  #           RUST_ARCH=x86_64-apple-darwin

  #     - name: Save Artefacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: wheel_${{ matrix.platform }}_${{ matrix.arch }}
  #         path: wheelhouse/*.whl

  publish:
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    needs:
      - build-sdist
      - build-linux-amd64
      - build-linux-aarch64
    steps:
      - name: Download Artefacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Prepare dist/
        run: |
          mv dist/*/*.whl dist/
          mv dist/*/*.tar.gz dist/
          find dist/* -type d | xargs rm -r

      - name: Show Artefacts
        run: ls -lhR dist/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
